[package]
name = "derive"
version = "0.0.0"
authors = ["Alexander Krigsman <alkrigsman@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
